enterlink/urls.py
from django.conf.urls import url, include
from enterlink import views, edit
from django.contrib.auth import views as django_views
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

# THIS LANGUAGE SETTING WORKS WHEN THE SETTINGS IS FORCED TO LANGUAGE_CODE = 'zh-hans'
# FOR SOME REASON, jsi18n IS NOT LANGUAGE AWARE
# jsi18n has an issue with Chinese since it is zh-hans. It works for ko and other two-character languages

urlpatterns = [
	url(ur'^$', views.index, name='index'),
	url(ur'^(?i)brainpower/(?P<account_name>(.*))/$', views.brainpowermgmt, name='brainpowermgmt'),
	url(ur'^(?i)rewards/(?P<account_name>(.*))/$', views.rewardsmgmt, name='rewardsmgmt'),
	url(ur'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
	url(ur'^(?i)contact/$', views.contact, name='contact'),
	url(ur'^(?i)investor-relations/$', views.investor_relations, name='investor_relations'),
	url(ur'^(?i)leadership/$', TemplateView.as_view(template_name="enterlink/leadership.html"), name='leadership'),
	url(ur'^(?i)exchange-listings/$', TemplateView.as_view(template_name="enterlink/exchange-listings.html"), name='exchange_listings'),
	url(ur'^(?i)transfer-iq/$', TemplateView.as_view(template_name="enterlink/transfer-iq.html"), name='transfer_iq'),
	url(ur'^(?i)editing-disabled/$', TemplateView.as_view(template_name="enterlink/editing-disabled.html"), name='editing_disabled'),
	url(ur'^(?i)recent-activity/$', views.recent_activity, name='recent_activity'),
	url(ur'^(?i)create_page/$', edit.create_page, name='create_page'),
	url(ur'^(?i)dropzone/$', views.dropzone, name='dropzone'),
	url(ur'^(?i)test_page/$', views.test_page, name='test_page'),
	url(ur'^(?i)error/$', views.error, name='error'),
	url(ur'^(?i)error404/$', TemplateView.as_view(template_name="enterlink/error.html"), name='error404'),
	url(ur'^(?i)cachefinalizedresult/(?P<proposal_id>(.*))/$', edit.cacheFinalizedResult, name='cacheFinalizedResult'),
    url(ur'^(?i)hoverblurb/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/$', views.hoverBlurb, name='hoverBlurb'),
	url(ur'^(?i)hoverblurb/(?P<url_param>(.*))/$', views.hoverBlurb, name='hoverBlurb'),
	url(ur'^(?i)language-selector/$', views.language_selector, name='language_selector'),
	url(ur'^(?i)search/$', views.search, name='search'),
	url(ur'^(?i)search/iframe/$', views.searchiframe, name='searchiframe'),
	url(ur'^favicon.ico/$', views.favicon, name='favicon'),
	url(ur'^robots\.txt$', TemplateView.as_view(template_name='enterlink/robots.txt', content_type='text/plain')),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Add_New_Infobox/$', edit.AJAX_Add_New_Infobox, name='AJAX_Add_New_Infobox'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Add_New_Link/$', edit.AJAX_Add_New_Link, name='AJAX_Add_New_Link'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_OREID_Auth/$', views.AJAX_OREID_Auth, name='AJAX_OREID_Auth'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Get_OREID_Token/$', views.AJAX_Get_OREID_Token, name='AJAX_Get_OREID_Token'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Group_Languages/(?P<sourceIPFS>(.*))/(?P<destinationIPFS>(.*))/$', edit.AJAX_Group_Languages, name='AJAX_Group_Languages'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Check_Blurb/$', views.AJAX_Check_Blurb, name='AJAX_Check_Blurb'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Create_Redirect/$', edit.AJAX_Create_Redirect, name='AJAX_Create_Redirect'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Fetch_Blurb_Compare/(?P<new_ipfs>(.*))/(?P<old_ipfs>(.*))/$', edit.AJAX_Fetch_Blurb_Compare, name='AJAX_Fetch_Blurb_Compare'),
	url(ur'^(?i)html-diff/(?P<new_ipfs>(.*))/(?P<old_ipfs>(.*))/$', edit.html_diff, name='html_diff'),
	url(ur'^(?i)text-diff/(?P<new_ipfs>(.*))/(?P<old_ipfs>(.*))/$', edit.text_diff, name='text_diff'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Fetch_New_Infobox_Form/(?P<url_param>(.*))/$', edit.AJAX_Fetch_New_Infobox_Form, name='AJAX_Fetch_New_Infobox_Form'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Fetch_Page_Photo/(?P<url_param>([0-9A-Za-z-_]{2,7}))/$', edit.AJAX_Fetch_Page_Photo, name='AJAX_Fetch_Page_Photo'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Hoverblurb/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/$', views.AJAX_Hoverblurb, name='AJAX_Hoverblurb'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Hoverblurb/(?P<url_param>(.*))/$', views.AJAX_Hoverblurb, name='AJAX_Hoverblurb'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Hoverlink/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/$', views.AJAX_Hoverlink, name='AJAX_Hoverlink'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Hoverlink/(?P<url_param>(.*))/$', views.AJAX_Hoverlink, name='AJAX_Hoverlink'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_QR_Code_Iframe/(?P<inputslug>(.*))/$', views.AJAX_QR_Code_Iframe, name='AJAX_QR_Code_Iframe'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_OREID_Callback/$', views.AJAX_OREID_Callback, name='AJAX_OREID_Callback'),
    url(ur'^(?i)AJAX-REQUEST/AJAX_OREID_Signing_Callback/$', edit.AJAX_OREID_Signing_Callback, name='AJAX_OREID_Signing_Callback'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Picture_Upload/(?P<photo_type>(.*))/(?P<identifier>(.*))/$', edit.AJAX_Picture_Upload, name='AJAX_Picture_Upload'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Schema_Search/$', views.AJAX_Schema_Search, name='AJAX_Schema_Search'),
	url(ur'^(?i)AJAX-REQUEST/AJAX_Search/(?P<url_param>(.*))/$', views.AJAX_Search, name='AJAX_Search'),
	url(ur'^(?i)pagecounter/(?P<page_slug>(.*))/$', views.pagecounter, name='pagecounter'),
	url(ur'^(?i)accounts/passwordreset/$', django_views.password_change, {'template_name' : 'admin/password_change_form.html'}, name='password_change'),
    url(ur'^(?i)account/reset/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(ur'^(?i)account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', django_views.password_reset_confirm, name='password_reset_confirm'),
    url(ur'^(?i)account/done/$', django_views.password_reset_complete, name='password_reset_complete'),
	url(ur'^(?i)account/reset/$', django_views.password_reset, name='password_reset'),
	url(ur'^(?i)wiki/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/edit/$', edit.edit, name='edit'),
	url(ur'^(?i)wiki/(?P<url_param>(.*))/edit/$', edit.edit, name='edit'),
	url(ur'^(?i)vote/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/$', edit.vote, name='vote'),
	url(ur'^(?i)sync_to_chain/$', edit.sync_to_chain, name='sync_to_chain'),
	url(ur'^(?i)check_new_articles/$', edit.check_new_articles, name='check_new_articles'),
	url(ur'^(?i)save_draft/$', edit.save_draft, name='save_draft'),
	url(ur'^(?i)get_draft/$', edit.get_draft, name='edit_draft'),
	url(ur'^(?i)wiki/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/amp/$', views.template_handler_blockchain, name='template_handler_blockchain'),
	url(ur'^(?i)wiki/(?P<url_param>([0-9A-Za-z-_]{2,7}))/amp/$', views.template_handler_blockchain, name='template_handler_blockchain'),
	# url(ur'^(?i)wiki/lang_(?P<lang_param>(.*))/(?P<url_param>(.*))/$', views.template_handler_blockchain, name='template_handler_blockchain'),
	url(ur'^(?i)wiki/lang_(?P<lang_param>([0-9A-Za-z-_]{2,7}))/(?P<url_param>(.*))/$', views.template_handler_blockchain, name='template_handler_blockchain'),

	url(ur'^(?i)wiki/(?P<url_param>(.*))/$', views.template_handler_blockchain, name='template_handler_blockchain'),
	url(ur'^(?P<url_param>(.*))/edit/$', views.edit_301, name='edit_301'),
	url(ur'^(?P<url_param>(.*))/amp/$', views.template_handler_301_amp, name='template_handler_301_amp'),
	url(ur'^(?P<url_param>(.*))/$', views.template_handler_301, name='template_handler_301'),

]

fbwiki/urls.py
import django
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin, auth
from django.contrib.sitemaps.views import sitemap, index
from django.contrib.auth import urls
from django.views import static
import registration, enterlink
from registration.backends import default
from enterlink import views as ENTERLINK_VIEWS
from enterlink.sitemap import ThisMonthsEdits_Sitemap
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import javascript_catalog
from registration.backends.default import urls
from enterlink import urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

#from django.views.generic import TemplateView #for robots.txt

import notifications

sitemaps_dict = {
	'edited-this-month':ThisMonthsEdits_Sitemap,
}



js_info_dict = {
    'domain': 'django',
    'packages': ('locale',),
}

handler400 = 'enterlink.views.error'
handler403 = 'enterlink.views.error'
handler404 = 'enterlink.views.error'
# Might want to have a custom server 500 search page
handler500 = 'enterlink.views.error'

urlpatterns = [
	url(ur'^karachi-admin/', include(admin.site.urls)),
	url(ur'^jsi18n/$', django.views.i18n.javascript_catalog, js_info_dict),
   	url(ur'^i18n/', include(django.conf.urls.i18n)),
   	# url(ur'^(?i)login/$', ENTERLINK_VIEWS.user_login, name='login'),
   	url(ur'^registration/', include(registration.backends.default.urls)),
	url(ur'', include(django.contrib.auth.urls)),
	url(r'^sitemap.xml/$', index, {'sitemaps': sitemaps_dict}, name='django.contrib.sitemaps.views.index'),
	url(r'^sitemap-(?P<section>.+).xml/$', sitemap, {'sitemaps': sitemaps_dict}, name='django.contrib.sitemaps.views.sitemap'),
	url(ur'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
   	url(ur'', include(enterlink.urls)),
]

# For development only
urlpatterns += staticfiles_urlpatterns()

enterlink/forms.py
# -*- coding: utf-8 -*-
import os
from django.forms import ModelForm
from enterlink.models import Contact
from django import forms
from django.utils.translation import ugettext_lazy
from fbwiki.settings import LANGUAGES

# "Contact Us" page
class ContactForm(ModelForm):
    contacttext = forms.CharField(max_length=16384, widget=forms.Textarea(attrs={'placeholder': ugettext_lazy('How can we help?')}))
    contactemail = forms.EmailField(max_length=512, widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Email')}))
    contactname = forms.CharField(max_length=512, widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Full Name')}))
    contactsubject = forms.CharField(max_length=512, widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Subject')}))
    contacttype = forms.ChoiceField(choices=(('Report Bug', ugettext_lazy('Report Abuse')), ('Report Bug', ugettext_lazy('Report Bug')), ('Verify Account', ugettext_lazy('Verify Account')), ('Anonymous Tip', ugettext_lazy('Anonymous Tip')), ('Investment Inquiries', ugettext_lazy('Investment Inquiries')), ('other', ugettext_lazy('Other'))))

    class Meta:
        model = Contact
        fields = ['contactsubject', 'contacttext', 'contacttype', 'contactemail', 'contactname']

# Search bar
class SearchBox(forms.Form):
    SearchBox = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Search by Entering a Link')}), max_length=512)

# New file additions
class NewlinkFileForm(forms.Form):
    linkcomment = forms.CharField(max_length=16384, widget=forms.Textarea(attrs={'placeholder': ugettext_lazy(
        'Describe the file briefly. A summary of the information found is best. Avoid simply repeating the page title.')}))
    file = forms.FileField()

    # Reject bad file types
    def clean_file(self):
        file = self.cleaned_data.get("file", False)
        base, extension = os.path.splitext(os.path.basename(file.name))
        extension = extension.upper()
        extension = extension[1:]
        badList = ['0XE', '73K', '89K', 'A6P', 'AC', 'ACC', 'ACR', 'ACTM', 'AHK', 'AIR', 'APP', 'ARSCRIPT', 'AS', 'ASB',
                   'AWK', 'AZW2', 'BEAM', 'BTM', 'CEL', 'CELX', 'CHM', 'COF', 'CRT', 'DEK', 'DLD', 'DMC', 'DMG', 'DXL',
                   'EAR', 'EBM', 'EBS', 'EBS2', 'ECF', 'EHAM', 'ELF', 'ES', 'EX4', 'EXOPC', 'EZS', 'FAS', 'FKY', 'FPI',
                   'FRS', 'FXP', 'GS', 'HAM', 'HMS', 'HPF', 'HTA', 'IIM', 'IPF', 'ISP', 'JAR', 'JS', 'JSX', 'KIX', 'LO',
                   'LS', 'MAM', 'MCR', 'MEL', 'MPX', 'MRC', 'MS', 'MS', 'MXE', 'NEXE', 'OBS', 'ORE', 'OTM', 'PEX',
                   'PLX', 'POTM', 'PPAM', 'PPSM', 'PRC', 'PVD', 'PWC', 'PYC', 'PYO', 'QPX', 'RBX', 'ROX', 'RPJ', 'S2A',
                   'SBS', 'SCA', 'SCAR', 'SCB', 'SCR', 'SCRIPT', 'SMM', 'SPR', 'TCP', 'THM', 'TLB', 'TMS', 'UDF', 'UPX',
                   'URL', 'VLX', 'VPM', 'WCM', 'WIDGET', 'WIZ', 'WPK', 'WPM', 'XAP', 'XBAP', 'XLAM', 'XLM', 'XQT',
                   'XYS', 'ZL9', 'ACTION', 'APK', 'APP', 'BAT', 'BIN', 'CMD', 'COM', 'COMMAND', 'CPL', 'CSH', 'EXE',
                   'GADGET', 'INF', 'INS', 'INX', 'IPA', 'ISU', 'JOB', 'JSE', 'KSH', 'LNK', 'MSC', 'MSI', 'MSP', 'MST',
                   'OSX', 'OUT', 'PAF', 'PIF', 'PRG', 'PS1', 'REG', 'RGS', 'RUN', 'SCT', 'SHB', 'SHS', 'U3P', 'VB',
                   'VBE', 'VBS', 'VBSCRIPT', 'WORKFLOW', 'WS', 'WSF']
        for badExt in badList:
            if badExt == extension:
                raise forms.ValidationError(ugettext_lazy("File type not allowed."))
        return file

# New link additions
class LinkForm(forms.Form):
    newlink_tag = None
    linkurl = forms.URLField(max_length=1024, min_length=1, error_messages={'required': ugettext_lazy('Please .')},
                             widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Enter a URL')}))
    linkcomment = forms.CharField(max_length=16384, widget=forms.Textarea(attrs={'placeholder': ugettext_lazy(
        'Describe the URL briefly. A summary of the information found is best. Avoid simply repeating the page title.')}))

# New infoboxes
class Infobox_Form_Tagged(forms.Form):
    infotype = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Enter type (e.g. Occupation)')}), required=False, max_length=2048)
    infocontent = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ugettext_lazy('Enter value (e.g. CEO)')}), required=False, max_length=2048)

# Page metadata
class PageMetaForm(forms.Form):
    page_type = forms.ChoiceField(required=False, choices=(
        ('Person', ugettext_lazy('Person')), ('Place', ugettext_lazy('Place/Location')),
        ('Organization', ugettext_lazy('Organization/Company/Institution')), ('Event', ugettext_lazy('Event')),
        ('ItemList', ugettext_lazy('List/Ranking')), ('Product', ugettext_lazy('Product/Merchandise')),
        ('Product', ugettext_lazy('Electronics/Software')), ('MedicalEntity', ugettext_lazy('Medical/Biology')),
        ('CreativeWork', ugettext_lazy('Creative Work/Art')),
        ('MedicalEntity', ugettext_lazy('Science/Academia/Humanities')), ('Thing', ugettext_lazy('Other')), (None, None)))
    is_removed = forms.BooleanField(required=False)
    is_adult_content = forms.BooleanField(required=False)
    page_lang = forms.ChoiceField(required=False, choices=LANGUAGES)


templates/enterlink/ajax_link_singlet.html
{% load i18n %}
{% load enterlink_custom_tags %}
<li class="link-row">
<table class="mce-item-table">
<tr>
    <td class="link-thumb-wrap">
        {% if theLink.mime != None or theLink.thumb != None %}
            <img class='link-thumb' src="{{ theLink.thumb }}" onerror="this.onerror=null;this.src='https://epcdn-vz.azureedge.net/static/images/white.png'"/>
        {% endif %}
    </td>
    <td class='link-details-wrap'>
        <table>
            <tr class='link-url-container-wrap'>
                <td class="link-url-citation-number no-edit">{{ theLink.integer }}</td>
                <td class="link-url-wrap">
                    <a class="link-url" {{ theLink.attr }} href="{{ theLink.url }}" target="_blank">{{ theLink.url }}</a>
                </td>
            </tr>
            <tr class="link-description-wrap">
                <td class="link-description">
                    {{ theLink.description|safe }}
                </td>
            </tr>
            <tr class="link-url-extra-wrap">
                <td class="link-url-extra-label no-edit">{% trans 'Social Media' %}</td>
                <td class="link-url-extra-value link-social-media">{{ theLink.isSocial }}</td>
                <td class="link-url-extra-label no-edit">{% trans 'Attributes' %}</td>
                <td class="link-url-extra-value link-attr">{{ linkChunk.attr }}</td>
                <td class="link-url-extra-label no-edit">{% trans 'Timestamp' %}</td>
                <td class="link-url-extra-value link-timestamp">{{ theLink.timestamp|json_fix_time }}</td>
                <td class="link-url-extra-label no-edit">MIME</td>
                <td class="link-url-extra-value link-mime">{{ theLink.mime}}</td>
            </tr>
        </table>
    </td>
</tr>
</table>
<div class="button-wrap">
    <div class="delete-btn-wrap">
        <span class="icon icon-squared-cross"></span>
    </div>
    <div class="add-btn-wrap">
        <span class="icon icon-squared-plus"></span>
    </div>
</div>
</li>

templates/enterlink/analytics.html
<!DOCTYPE html>

{% load i18n %}
<html>
    <head>

    <title>{% trans "Frequently Asked Questions - Everipedia, everyone's encyclopedia" %}</title>
    <!-- ' -->
    <meta name="description" content="Everipedia is the world’s largest collection of hyperlinks grouped by identity. ">
    <link rel="canonical" href="https://everipedia.org/everipedia-faq/" />
	<!--- Include Header -->
	{% include "enterlink/headers/header-common.html" %}{% include "enterlink/headers/header-navbar.html" %}
    <link href="/static/css/howto_welcome.css" rel="stylesheet">
 		
	<div class="container" id="abt-ct" style="margin-top:40px;">
		<div class="panel panel-default">
			<!-- Step 1: Create the containing elements. -->

            <section id="auth-button"></section>
            <section id="view-selector"></section>
            <section id="timeline"></section>

            <!-- Step 2: Load the library. -->

            <script>
            (function(w,d,s,g,js,fjs){
              g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(cb){this.q.push(cb)}};
              js=d.createElement(s);fjs=d.getElementsByTagName(s)[0];
              js.src='https://apis.google.com/js/platform.js';
              fjs.parentNode.insertBefore(js,fjs);js.onload=function(){g.load('analytics')};
            }(window,document,'script'));
            </script>

            <script>
            gapi.analytics.ready(function() {

              // Step 3: Authorize the user.

              var CLIENT_ID = '837540067179-oucpg176lq2dkbu4bnmiemefpumabcs6.apps.googleusercontent.com';

              gapi.analytics.auth.authorize({
                container: 'auth-button',
                clientid: CLIENT_ID,
              });

              // Step 4: Create the view selector.

              var viewSelector = new gapi.analytics.ViewSelector({
                container: 'view-selector'
              });

              // Step 5: Create the timeline chart.

              var timeline = new gapi.analytics.googleCharts.DataChart({
                reportType: 'ga',
                query: {
                  'dimensions': 'ga:date',
                  'metrics': 'ga:sessions',
                  'start-date': '30daysAgo',
                  'end-date': 'yesterday',
                },
                chart: {
                  type: 'LINE',
                  container: 'timeline'
                }
              });

              // Step 6: Hook up the components to work together.

              gapi.analytics.auth.on('success', function(response) {
                viewSelector.execute();
              });

              viewSelector.on('change', function(ids) {
                var newIds = {
                  query: {
                    ids: ids
                  }
                }
                timeline.set(newIds).execute();
              });
            });
            </script>
			</div>
		</div>
	</div>

<!--- Everipedia Footer -->
{% include "enterlink/footers/footer.html" %}

templates/enterlink/contact.html
<!DOCTYPE html>
{% load i18n %}
<html>
<head>
    <title>{% trans 'Contact us' %} - {% trans "Everipedia, the encyclopedia of everything" %}</title>
    <!-- ' -->
    <meta name="description" content=" Everipedia is the world’s largest collection of hyperlinks grouped by identity. ">
	<link rel="canonical" href="https://everipedia.org/contact/" />
	<!--- Include Header -->
	{% include "enterlink/headers/header-common.html" %}{% include "enterlink/headers/header-navbar.html" %}
    <link href="/static/css/howto_welcome.css" rel="stylesheet">
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
	<div class="contact-ct tablet-compatible">
		<h1>{% trans 'Contact us' %}</h1>
		<h4>{% trans 'Get in touch with us' %}</h4>
        <ul class="address-list">
            <li>Everipedia International</li>
            <li>171 Elgin Avenue</li>
            <li>Floor 2 #709, Willow House, Cricket Square</li>
            <li>Grand Cayman, KY1-1103</li>
            <li>Cayman Islands</li>
        </ul>
		{% if sent %}<div class="alert alert-success"><strong>{% trans 'Thanks, we got your message. We will respond in a bit' %}.</strong></div>{% endif %}
		
		{% if sent == False %}
			<form id="contact_form" method="POST" action="/contact/">
			    {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}

			    <span style="color:darkred;">{% for field in form.visible_fields %} {{ field.errors }} {{ field.help_text }} {{ field }} {% endfor %}</span>
                <div class="g-recaptcha" data-sitekey="6LdqkGQUAAAAABok67o8I1NW0-Mlif_KGyVhEdIH"></div>
			    <input type="submit" class="btn btn-info pull-left" name="submit" value="{% trans 'Send' %}" />
            </form>
		{% endif %}
		
	</div>

<!--- Everipedia Footer -->
{% include "enterlink/footers/footer.html" %}
{#{% include "enterlink/footers/deferredJS.html" %}#}
{% include 'enterlink/inline-css/application.html' %}
{% include 'enterlink/headers/extra-analytics-right-before-body-end.html' %}
</body>
</html>

templates/enterlink/edit_ajax_editpagemeta.html
{% load i18n %}
{% load enterlink_custom_tags %}

<div class="topic-select-instructions">{% trans "Select the topic of this page" %}:</div>
<div class="page_type">{{pagemetaform.page_type}}</div>
<!--<div class="subpage_type">{{pagemetaform.subpage_type}}</div>-->
<span id="edit_remove" class="checkbox-container">
    {% trans "Remove page" %}: {{pagemetaform.is_removed}}
    <label for="id_is_removed"></label>
</span>
<span id="edit_remove" class="checkbox-container">
    {% trans "Adult Content" %}: {{pagemetaform.is_adult_content}}
    <label for="id_is_adult_content"></label>
</span>
<div class="page_lang">{{pagemetaform.page_lang}}</div>
<button id="pagemeta-closepagemetabtn" class="pagemeta-close-button" onclick="hidePageMetaPane();" type="button" name="closepagemetabtn">{% trans "Close" %}</button>


<script>
    function hidePageMetaPane() {
        $("#pagemeta-box-wrapper").hide();
    }
</script>